run:
  timeout: 3m
  skip-dirs:
    - controllers/machinerequest/* # TODO: This should be fixed ASAP

linters:
  enable:
    - revive
    - ineffassign
    - misspell
    - goimports

severity:
  default-severity: error

linters-settings:
  misspell:
    ignore-words:
      - strat
  revive:
    severity: error
    rules:
      - name: exported
      - name: if-return
        disabled: true
