
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compute.onmetal.de
  resources:
  - machineclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compute.onmetal.de
  resources:
  - machinepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compute.onmetal.de
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.onmetal.de
  resources:
  - machines/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - compute.onmetal.de
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.onmetal.de
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.onmetal.de
  resources:
  - storagepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.onmetal.de
  resources:
  - volumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.onmetal.de
  resources:
  - volumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.onmetal.de
  resources:
  - volumes/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - storage.onmetal.de
  resources:
  - volumes/status
  verbs:
  - get
  - patch
  - update
